name: Android APK Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları Depodan Çek
        uses: actions/checkout@v4

      - name: Node.js Ortamını Kur
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Proje Bağımlılıklarını Yükle
        run: |
          npm install

      - name: Java (JDK 17) Ortamını Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Android SDK ve Build Tools Ortamını Hazırla
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-33" "build-tools;33.0.2" "platform-tools"

      - name: Capacitor Android Paketini Derle
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Gradle ile Debug APK Oluştur ve Yeniden Adlandır
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/GPS-Takip.apk

      - name: APK Dosyasını Kaydet (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: GPS Takip
          path: android/app/build/outputs/apk/debug/GPS-Takip.apk
          
